[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["...","node"]}

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "Node PNPtvLiveApp.js"
sleepApplication = false
multiRegionConfig = {"us-east4-eqdc4a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
